# Nom de l'application Spring Boot
spring.application.name=budget-tracker-api

# URL de connexion à la base H2 en mémoire
spring.datasource.url=jdbc:h2:mem:budget_tracker

# Driver utilisé par H2
spring.datasource.driver-class-name=org.h2.Driver

# Nom d'utilisateur H2
spring.datasource.username=sa

# Mot de passe H2 vide
spring.datasource.password=

# Hibernate met à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL dans la console
spring.jpa.show-sql=true

# Active la console web H2
spring.h2.console.enabled=true

# URL de la console H2
spring.h2.console.path=/h2-console